name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push en la rama main
  workflow_dispatch:  # Permitir ejecución manual del flujo de trabajo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js si es necesario (opcional, si usas Node.js en el proyecto)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Paso 3: Instalar dependencias (si es necesario para tu proyecto)
      - name: Install dependencies
        run: npm install

      # Paso 4: Construir el sitio (reemplaza este paso con tu comando de construcción)
      - name: Build the project
        run: npm run build

      # Paso 5: Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Reemplaza "./public" con la carpeta donde se generan tus archivos
